{
    'name': 'sid_activity_enhance',
    'version': '15.0.2.1.0',
    'category': 'Sales',
    'summary': 'Rebase estable de sale.activity respetando la mecánica original.',
    'author': 'oscarsidsa81',
    'license': 'LGPL-3',
    'depends': [
        'sale',
        'stock',
        'purchase',
        'oct_so_line_info',
        'sid_sale_line_views_ov',
        'sid_purchase_delay_sync',
        'oct_certificate_receptions',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sid_activity_tags.xml',
        'views/sale_activity_views.xml',
        'views/sale_activity_tag_rule_views.xml',
        'views/sale_line_activity_wizard_views.xml',
        'views/sale_line_activity_integration_views.xml',
        'views/sale_order_line_tag_views.xml',
        'views/stock_move_tag_views.xml',
        'views/stock_picking_tag_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
}
